apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: postgresdynamic
  labels:
    app: postgresdynamic
    role: master
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: postgresdynamic
        role: master
    spec:
      containers:
      - name: postgresdynamic
        image: postgres
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_PASSWORD
          value: "Password123!"
        volumeMounts:
        - name: postgresdynamic
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgresdynamic
        persistentVolumeClaim:
          claimName: pvc-sio-small
