kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: sio-small
provisioner: kubernetes.io/scaleio
parameters:
  gateway: https://192.168.50.12:443/api
  system: cluster1
  protectionDomain: pdomain
  storagePool: pool1
  readOnly: "false"
  secretRef: sio-secret
